### ISSUE TITLE
Errors on downloading endf data while running `cstool pmma.yaml`

### ISSUE THREAD

**Issue by wak-shogo** [Nebula-simulator/cstool#2]
`obtain_endf_files.py` caused 404 errors.
It seems like that the endf URLs have been changed on www.nndc.bnl.gov.

On [https://www.nndc.bnl.gov/endf-b7.1/download.html](https://www.nndc.bnl.gov/endf-b7.1/download.html), the zip file path is no longer `endf/b7.1`, but `endf-b7.1`.

Modifying the three urls on `cstool/data/endf_sources.json` and re-installing cstool resolved this problem.

Would you please repair the url on `endf_sources.json` ?

**Comment by lvkessel** [comment]
Thanks for the heads up! Fixed.
