### ISSUE TITLE
Unclear meaning of "valence" parameter

### ISSUE THREAD

**Issue by hsuominen** [Nebula-simulator/cstool#3]
In the docs it is stated that the valence parameter is "the width of the valence band". 

Looking at the sample datasets though it seems that for Alumina the value used is the valence band maximum (3.64eV), while the reported valence band width elsewhere seems to be on the order ~8eV.

In contrast for Silicon it seems that the valence parameter is likely the width, though it was hard to find a reference value in literature.

Digging into the code here I am also a bit unsure how to interpret the parameter:
https://github.com/Nebula-simulator/cstool/blob/3d5f6636bdf2b2ce2578e62b93e1d87fe019faac/cstool/input_data/band_structure.py#L31-L60 

Naively I would have expected e.g. the minimum excitation energy to be simply `affinity + 2*band_gap`

**Comment by lvkessel** [comment]
"The width of the valence band" refers to the energy difference between the top and the bottom of the valence band. It seems that the paper referenced in the alumina.yaml file was misinterpreted. Eyeballing figure 3 in that paper, 8 eV looks like a more reasonable value indeed. Good catch!

The code you quote refers to the Fermi parameter, but I think you are asking about the minimum excitation energy. This is the minimum energy an electron must have (with respect to the bottom of the valence band) to excite a secondary electron. It must have at least the valence band width plus two times the band gap: the electron itself must not fall below valence+bandgap; and it must at least be able to push the secondary electron across the band gap.

The goal of the min_excitation function here is to provide a lower bound for an integral somewhere. If this minimal criterium is met precisely, then both electrons will end up at the bottom of the conduction band, which is not enough to escape the material. A different piece of code is responsible for removing these electrons from the simulation if that happens.
