### ISSUE TITLE
ImportError: cannot import name 'trapz' from 'scipy.integrate'

### ISSUE THREAD

**Issue by fatimaanis** [Nebula-simulator/cstool#4]
When running the cstool, I get the following error.

ImportError: cannot import name 'trapz' from 'scipy.integrate'

**Comment by lvkessel** [comment]
Right, yeah, that function has been renamed. I have seen the deprecation warning for a while but I never got round to fixing it here. If you need a quick fix you can downgrade scipy to version 1.13 or below; I will fix it in this repository later this week.
